services:
  server:
    build:
      context: ./server
      target: build
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
