services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    build:
      context: ./server
      target: build
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE:  postgres
    command: npm run dev
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      target: build
    command: npm run dev
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    depends_on:
      - server

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - server
      - client